### ISSUE TITLE
Basic usage example

### ISSUE THREAD

**Issue by MaksymDel** [chrishokamp/constrained_decoding#3]
Hi @chrishokamp @laeubli , thank you for the nice contribution! :+1:

Could you please provide a simple example on how to run your GBS with Nematus model? 

This way your tool will be more accessible.

**Comment by chrishokamp** [comment]
@maxdel, sure I'll add an example today

**Comment by chrishokamp** [comment]
i've added an example with a nematus model to the [README](https://github.com/chrishokamp/constrained_decoding), if you have any issue please reopen the issue :wink:
