### ISSUE TITLE
MatchSpotter from semantic_annotator.spotting

### ISSUE THREAD

**Issue by bsbor** [chrishokamp/constrained_decoding#4]
Hi,

Is it possible to have access to  MatchSpotter from semantic_annotator.spotting ?
Or could you please tell me what is inside the object returned by the get_spots() function ?

Thank you in advance :)

**Comment by chrishokamp** [comment]
whoops! sorry i missed the issue notification from GH. This should be fixed now, please reopen if you have problems/questions

**Comment by chrishokamp** [comment]
just a note, you need to do `pip install pyahocorasick` for the spotter to work

**Comment by bsbor** [comment]
Thanks a lot ! It's working like a charm :)
