### ISSUE TITLE
ImportError: No module named theano_util

### ISSUE THREAD

**Issue by ArleneYuZhiwei** [chrishokamp/constrained_decoding#5]
I installed Nematus and run your code according to your README but got errors as follows: constrained_decoding/constrained_decoding/translation_model/nematus_tm.py
, line 15, in <module>
    from nematus.theano_util import (load_params, init_theano_params)
ImportError: No module named theano_util
I read the source code of Nematus("https://github.com/EdinburghNLP/nematus/tree/master/nematus")  and found there are no module named theano_util.
What's more constrained_decoding/constrained_decoding/translation_model/nematus_tm.py , line 16, in <module>
    from nematus.nmt import (build_sampler, gen_sample, init_params)
ImportError: cannot import name build_sampler
I cannot solve the problem above, please correct me if I misunderstood something. Thank you for your patience.

**Comment by chrishokamp** [comment]
Hi thanks for the bug report, apparently that file was removed from nematus

Can you try doing:
```
cd <nematus_install_dir>
git checkout d8f4384151c4ee4a0bcd4e773981fe97b0f0f1f0
pip install -e . 
```

If that works, I'll add to docs.

**Comment by chrishokamp** [comment]
btw you can see the Nematus code at that commit here: https://github.com/EdinburghNLP/nematus/tree/d8f4384151c4ee4a0bcd4e773981fe97b0f0f1f0/nematus

**Comment by ArleneYuZhiwei** [comment]
Thank you for your help. It solved the problem I met before, however there is a new bug:
 File "/nematus/nmt.py", line 609, in build_sampler
   if options['deep_fusion_lm']:
KeyError: 'deep_fusion_lm'
I checked nmt.py and find nothing wrong. Do you know how to fix this bug?
thank you:)
Best Wishes

在2018-07-12 23:51:38，yuzhiwei1701214304@pku.edu.cn写道：

Hi thanks for the bug report, apparently that file was removed from nematus

Can you try doing:

cd <nematus_install_dir>
git checkout d8f4384151c4ee4a0bcd4e773981fe97b0f0f1f0
pip install -e . 


If that works, I'll add to docs.

**Comment by chrishokamp** [comment]
> I checked nmt.py and find nothing wrong. Do you know how to fix this bug?

This error means that the the key `deep_fusion_lm` does not exist in the model options, so the commit we checked out is still broken for constrained decoding. Apparently that was a bug that was fixed in the [following commit](https://github.com/EdinburghNLP/nematus/commit/0ea2cd1870f9f12a2f53837da3bc3f01f1ea8a5f).

So try:
```
cd <nematus_install_dir>
git checkout 0ea2cd1870f9f12a2f53837da3bc3f01f1ea8a5f
```

I also saw [your issue](https://github.com/EdinburghNLP/nematus/issues/76) in the Nematus repo, but I suggest you close it, since you're asking about an outdated version of their codebase. I don't plan to update this repo for the current version of their codebase, but if this hack works, I'll add it to the README.

**Comment by ArleneYuZhiwei** [comment]
Thank you very much.But I am outside for a trip now I will delete that issue as soon as possible.
best wishes~


在 2018-07-13 18:00:46，"Chris Hokamp" <notifications@github.com> 写道：

**Comment by rsennrich** [comment]
I suggest you point people to the theano branch of Nematus in your README: https://github.com/EdinburghNLP/nematus/tree/theano

**Comment by chrishokamp** [comment]
@rsennrich cheers, that's much easier :smile:, should be fixed now.
