### ISSUE TITLE
How to train a model?

### ISSUE THREAD

**Issue by Wangzhiyang96** [chrishokamp/constrained_decoding#6]
First of all, thank you for sharing. According to the example you give, I can run and get the result of constrained translation. But I don't know how to train a constrained translation model. And I don't know how to operate when I want to change the corpus.

**Comment by chrishokamp** [comment]
Hi this repo is no longer maintained, but constrained decoding is just about inference time, nothing needs to change about training. So if you just train a nematus model (in the `theano` branch), it can be used in the same way as the example workflow. 

For a faster implementation with more features check out sockeye https://github.com/awslabs/sockeye

**Comment by Wangzhiyang96** [comment]
Thank you for your quick reply. I see what you mean and thank you again.
